import type { BookItem } from '../_types/bookshelf.type';

export const BOOKSHELF_MOCK: BookItem[] = [
  {
    id: '1',
    title: '브람스를 좋아하세요…',
    author: '프랑수아즈 사강',
    publisher: '민음사',
    pages: 160,
    coverUrl: '/src/assets/book-sample.svg',
    isLiked: true,
    status: 'reading',
    progressPercent: 100,
    currentPage: 160,
  },
  {
    id: '2',
    title: '브람스를 좋아하세요…',
    author: '프랑수아즈 사강',
    publisher: '민음사',
    pages: 160,
    coverUrl: '/src/assets/book-sample.svg',
    isLiked: false,
    status: 'reading',
    progressPercent: 30,
    currentPage: 48,
  },
  {
    id: '3',
    title: '요리코를 위해',
    author: '요시모토 바나나',
    publisher: '민음사',
    pages: 240,
    coverUrl: '/src/assets/book-sample.svg',
    isLiked: true,
    status: 'finished',
    progressPercent: 100,
    currentPage: 240,
  },
  {
    id: '4',
    title: '브람스를 좋아하세요…',
    author: '프랑수아즈 사강',
    publisher: '민음사',
    pages: 160,
    coverUrl: '/src/assets/book-sample.svg',
    isLiked: false,
    status: 'reading',
    progressPercent: 10,
    currentPage: 16,
  },
  {
    id: '5',
    title: '아가씨와 밤',
    author: '기욤 뮈소',
    publisher: '밝은세상',
    pages: 320,
    coverUrl: '/src/assets/book-sample.svg',
    isLiked: true,
    status: 'reading',
    progressPercent: 75,
    currentPage: 240,
  },
  {
    id: '6',
    title: '지구 끝의 온실',
    author: '김초엽',
    publisher: '자이언트북스',
    pages: 360,
    coverUrl: '/src/assets/book-sample.svg',
    isLiked: false,
    status: 'finished',
    progressPercent: 100,
    currentPage: 360,
  },
  {
    id: '7',
    title: '달러구트 꿈 백화점',
    author: '이미예',
    publisher: '팩토리나인',
    pages: 280,
    coverUrl: '/src/assets/book-sample.svg',
    isLiked: true,
    status: 'reading',
    progressPercent: 50,
    currentPage: 140,
  },
  {
    id: '8',
    title: '아몬드',
    author: '손원평',
    publisher: '창비',
    pages: 260,
    coverUrl: '/src/assets/book-sample.svg',
    isLiked: false,
    status: 'reading',
    progressPercent: 0,
    currentPage: 0,
  },
  {
    id: '9',
    title: '불편한 편의점',
    author: '김호연',
    publisher: '나무옆의자',
    pages: 250,
    coverUrl: '/src/assets/book-sample.svg',
    isLiked: true,
    status: 'liked',
    progressPercent: 0,
    currentPage: 0,
  },
];
